import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning, module="langgraph")

import asyncio
import json
from concurrent.futures import ThreadPoolExecutor

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse

from graph.debate_graph import build_graph, DebateGraphState
from schemas import DebateRequest, DebateResponse

_executor = ThreadPoolExecutor(max_workers=2)
TIMEOUT_SECONDS = 300

app = FastAPI(
    title="Debate Chatbot API",
    description="Real-time multi-agent debate chatbot with memory.",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_tags=[
        {"name": "Debate", "description": "Debate pipeline"},
        {"name": "Health", "description": "Server health checks"},
    ],
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

_graph = build_graph()

TURN_LABELS = {
    "pro_opening":  "🎤 Pro Agent is presenting opening arguments...",
    "con_opening":  "🎤 Con Agent is presenting opening arguments...",
    "pro_rebuttal": "⚔️  Pro Agent is rebutting...",
    "con_rebuttal": "⚔️  Con Agent is rebutting...",
    "pro_closing":  "🏁 Pro Agent is giving closing remarks...",
    "con_closing":  "🏁 Con Agent is giving closing remarks...",
    "moderator":    "⚖️  Moderator is evaluating...",
}

AGENT_NODES = {
    "pro_opening":  "Pro",
    "con_opening":  "Con",
    "pro_rebuttal": "Pro",
    "con_rebuttal": "Con",
    "pro_closing":  "Pro",
    "con_closing":  "Con",
}


# ---------------------------------------------------------------------------
# Streaming debate — token by token
# ---------------------------------------------------------------------------

@app.post("/debate/stream", tags=["Debate"], summary="Run a debate with streaming output")
async def debate_stream(request: DebateRequest):
    """
    Streams tokens as they are generated by the LLM using astream_events.
    - on_chain_start  → send label when a new agent node begins
    - on_llm_new_token → send each token as it arrives (true live streaming)
    - on_chain_end    → send result when moderator finishes
    """
    async def event_generator():
        initial_state: DebateGraphState = {
            "topic": request.topic,
            "past_debates": [],
            "current_turn": "",
            "pro_opening": "",
            "con_opening": "",
            "pro_rebuttal": "",
            "con_rebuttal": "",
            "pro_closing": "",
            "con_closing": "",
            "winner": "",
            "summary": "",
        }

        current_node = None

        try:
            async for event in _graph.astream_events(initial_state, version="v2"):
                kind = event["event"]
                name = event.get("name", "")

                # New agent node starting — send label
                if kind == "on_chain_start" and name in TURN_LABELS:
                    current_node = name
                    label = TURN_LABELS[name]
                    yield f"data: {json.dumps({'type': 'label', 'text': label, 'node': name})}\n\n"

                # LLM token arriving — send immediately
                elif kind == "on_chat_model_stream" and current_node in AGENT_NODES:
                    token = event["data"]["chunk"].content
                    if token:
                        yield f"data: {json.dumps({'type': 'token', 'side': AGENT_NODES[current_node], 'node': current_node, 'token': token})}\n\n"

                # Moderator finished — send final result
                elif kind == "on_chain_end" and name == "moderator":
                    output = event["data"].get("output", {})
                    if isinstance(output, dict) and output.get("winner"):
                        yield f"data: {json.dumps({'type': 'result', 'winner': output['winner'], 'summary': output['summary']})}\n\n"

        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"

        yield "data: [DONE]\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={"X-Accel-Buffering": "no", "Cache-Control": "no-cache"},
    )


# ---------------------------------------------------------------------------
# Non-streaming debate
# ---------------------------------------------------------------------------

@app.post("/debate", response_model=DebateResponse, tags=["Debate"], summary="Run a debate")
async def debate(request: DebateRequest):
    initial_state: DebateGraphState = {
        "topic": request.topic,
        "past_debates": [],
        "current_turn": "",
        "pro_opening": "",
        "con_opening": "",
        "pro_rebuttal": "",
        "con_rebuttal": "",
        "pro_closing": "",
        "con_closing": "",
        "winner": "",
        "summary": "",
    }
    try:
        loop = asyncio.get_event_loop()
        result = await asyncio.wait_for(
            loop.run_in_executor(_executor, _graph.invoke, initial_state),
            timeout=TIMEOUT_SECONDS,
        )
    except asyncio.TimeoutError:
        raise HTTPException(status_code=504, detail="Debate timed out.")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    return DebateResponse(
        topic=result["topic"],
        winner=result["winner"],
        summary=result["summary"],
    )


# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------

@app.get("/health", tags=["Health"], summary="Health check")
def health():
    return {"status": "ok"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)
